// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Smoothie.Web.Controllers {
    public partial class HomeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Summary() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Summary);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Blender() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Blender);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.PartialViewResult UserProfile() {
            return new T4MVC_PartialViewResult(Area, Name, ActionNames.UserProfile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetCategory() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult SearchIngredients() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.SearchIngredients);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Summary = "Summary";
            public readonly string Blender = "Blender";
            public readonly string About = "About";
            public readonly string UserProfile = "UserProfile";
            public readonly string GetCategory = "GetCategory";
            public readonly string SearchIngredients = "SearchIngredients";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string Summary = "Summary";
            public const string Blender = "Blender";
            public const string About = "About";
            public const string UserProfile = "UserProfile";
            public const string GetCategory = "GetCategory";
            public const string SearchIngredients = "SearchIngredients";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index {
            public readonly string userData = "userData";
            public readonly string category = "category";
        }
        static readonly ActionParamsClass_Summary s_params_Summary = new ActionParamsClass_Summary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Summary SummaryParams { get { return s_params_Summary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Summary {
            public readonly string form = "form";
            public readonly string userData = "userData";
            public readonly string smoothieId = "smoothieId";
            public readonly string category = "category";
        }
        static readonly ActionParamsClass_Blender s_params_Blender = new ActionParamsClass_Blender();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Blender BlenderParams { get { return s_params_Blender; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Blender {
            public readonly string smoothieId = "smoothieId";
        }
        static readonly ActionParamsClass_UserProfile s_params_UserProfile = new ActionParamsClass_UserProfile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserProfile UserProfileParams { get { return s_params_UserProfile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserProfile {
            public readonly string userData = "userData";
        }
        static readonly ActionParamsClass_GetCategory s_params_GetCategory = new ActionParamsClass_GetCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCategory GetCategoryParams { get { return s_params_GetCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCategory {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SearchIngredients s_params_SearchIngredients = new ActionParamsClass_SearchIngredients();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchIngredients SearchIngredientsParams { get { return s_params_SearchIngredients; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchIngredients {
            public readonly string term = "term";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _UserProfile = "~/Views/Home/_UserProfile.cshtml";
            public readonly string About = "~/Views/Home/About.cshtml";
            public readonly string Blender = "~/Views/Home/Blender.cshtml";
            public readonly string GetCategory = "~/Views/Home/GetCategory.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Summary = "~/Views/Home/Summary.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_HomeController: Smoothie.Web.Controllers.HomeController {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(Smoothie.Domain.Dto.UserDataDto userData, int category) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userData", userData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Summary(System.Web.Mvc.FormCollection form, Smoothie.Domain.Dto.UserDataDto userData, int smoothieId, int category) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Summary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "form", form);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userData", userData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "smoothieId", smoothieId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Blender(int smoothieId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Blender);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "smoothieId", smoothieId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult About() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.About);
            return callInfo;
        }

        public override System.Web.Mvc.PartialViewResult UserProfile(Smoothie.Domain.Dto.UserDataDto userData) {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.UserProfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userData", userData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetCategory(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult SearchIngredients(string term) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.SearchIngredients);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
